import industrial0 from './embedded/industrial-0.js'
import measurement0 from './embedded/measurement-0.js'
import observability0 from './embedded/observability-0.js'
import observability1 from './embedded/observability-1.js'
import observability2 from './embedded/observability-2.js'
import observability3 from './embedded/observability-3.js'
import cv0 from './embedded/cv-0.js'
import cv1 from './embedded/cv-1.js'
